{
  "hash": "2ec8489cf1721f23e74a9d37fd84ff70",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"BlogPost6\"\ndescription:  |\n  Our sixth blog post containing the combination of two datasets\nauthor: \"Team 10 (Mango)\"\ndate: \"2025-04-14\"\nformat: html\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(readr)\n\nchicago_crime_data <- read_csv(\"/Users/wmh/Desktop/MA415/Project Team 10/dataset-ignore/Crimes_-_2001_to_Present.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 8293608 Columns: 22\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (12): Case Number, Date, Block, IUCR, Primary Type, Description, Locatio...\ndbl  (8): ID, Ward, Community Area, X Coordinate, Y Coordinate, Year, Latitu...\nlgl  (2): Arrest, Domestic\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nchicago_clean <- chicago_crime_data %>%\n  filter(Year >= 2001, !is.na(Year)) %>%\n  filter(`Primary Type` %in% c(\"HOMICIDE\", \"CRIM SEXUAL ASSAULT\", \"ROBBERY\", \"BURGLARY\", \"SEX OFFENSE\")) %>%\n  group_by(Year, `Primary Type`) %>%\n  summarise(Crime_Count = n(), .groups = \"drop\")\nchicago_clean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 120 × 3\n    Year `Primary Type`      Crime_Count\n   <dbl> <chr>                     <int>\n 1  2001 BURGLARY                  26014\n 2  2001 CRIM SEXUAL ASSAULT        1774\n 3  2001 HOMICIDE                    667\n 4  2001 ROBBERY                   18441\n 5  2001 SEX OFFENSE                2239\n 6  2002 BURGLARY                  25623\n 7  2002 CRIM SEXUAL ASSAULT        1802\n 8  2002 HOMICIDE                    658\n 9  2002 ROBBERY                   18523\n10  2002 SEX OFFENSE                2173\n# ℹ 110 more rows\n```\n\n\n:::\n:::\n\n\nSince the Chicago dataset is very huge, to prepare the Chicago crime dataset for comparison with the exoneration data, we first filtered the full dataset only include records from 2001 onward, aligning with the time span of our analysis. We further narrowed the dataset to focus on five major crime categories relevant to potential wrongful convictions: HOMICIDE, CRIM SEXUAL ASSAULT, ROBBERY, BURGLARY, and SEX OFFENSE. These categories were selected based on their severity and overlap with crimes most often associated with exonerations. After filtering, we grouped the data by year and crime type, and counted the number of reported incidents per group. This resulted in a clean, aggregated table of 120 rows (24 years × 5 crime types), which provides a structured yearly summary of serious criminal activity in Chicago. This cleaned data will enable meaningful comparison with the exoneration dataset by aligning both sources on a common yearly time frame and crime category structure.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexoneration_data <- read_csv(\"/Users/wmh/Desktop/MA415/Project Team 10/dataset/publicspreadsheet.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 3658 Columns: 22\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (18): Last Name, First Name, Race, Sex, State, County, Tags, Worst Crime...\ndbl  (3): Age, Convicted, Exonerated\nnum  (1): Date of Crime Year\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nexon_clean <- exoneration_data %>%\n  filter(County == \"Cook\", !is.na(Convicted)) %>%\n  filter(Convicted >= 2001)\n\nexon_yearly <- exon_clean %>%\n  group_by(Year = Convicted, `Worst Crime Display`) %>%\n  summarise(Exoneration_Count = n(), .groups = \"drop\")\n\ncrime_mapping <- tibble(\n  `Worst Crime Display` = c(\"Murder\", \"Sexual Assault\", \"Robbery\", \"Theft\", \"Sex Offense\"),\n  `Primary Type` = c(\"HOMICIDE\", \"CRIM SEXUAL ASSAULT\", \"ROBBERY\", \"BURGLARY\", \"SEX OFFENSE\")\n)\n\nexon_mapped <- exon_yearly %>%\n  inner_join(crime_mapping, by = \"Worst Crime Display\")\ncombined_panel <- chicago_clean %>%\n  inner_join(exon_mapped, by = c(\"Year\", \"Primary Type\"))\n\ncombined_panel\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 5\n    Year `Primary Type`      Crime_Count `Worst Crime Display` Exoneration_Count\n   <dbl> <chr>                     <int> <chr>                             <int>\n 1  2001 HOMICIDE                    667 Murder                                7\n 2  2002 BURGLARY                  25623 Theft                                 1\n 3  2002 HOMICIDE                    658 Murder                                4\n 4  2003 HOMICIDE                    604 Murder                                2\n 5  2004 CRIM SEXUAL ASSAULT        1527 Sexual Assault                        1\n 6  2004 HOMICIDE                    455 Murder                                3\n 7  2005 HOMICIDE                    453 Murder                                4\n 8  2006 HOMICIDE                    478 Murder                                5\n 9  2007 HOMICIDE                    448 Murder                                2\n10  2009 HOMICIDE                    461 Murder                                2\n11  2011 HOMICIDE                    438 Murder                                4\n12  2012 HOMICIDE                    515 Murder                                1\n13  2012 ROBBERY                   13484 Robbery                               1\n14  2013 BURGLARY                  17894 Theft                                 1\n15  2014 HOMICIDE                    429 Murder                                3\n16  2017 BURGLARY                  13001 Theft                                 1\n17  2017 HOMICIDE                    676 Murder                                1\n18  2018 HOMICIDE                    600 Murder                                1\n19  2019 HOMICIDE                    509 Murder                                1\n20  2020 HOMICIDE                    796 Murder                                1\n```\n\n\n:::\n:::\n\n\nTo prepare the exoneration dataset for comparison with Chicago crime data, we began by filtering the data to include only individuals convicted in Cook County from the year 2001 onward, aligning with the temporal scope of the crime dataset. We grouped the filtered data by conviction year and the variable Worst Crime Display, which indicates the most serious offense in each case, and calculated the number of exonerations per year for each crime type. To enable a valid comparison, we created a mapping table that aligns exoneration crime categories (e.g., \"Murder\", \"Sexual Assault\") with the Primary Type categories used in the Chicago crime dataset (e.g., \"HOMICIDE\", \"CRIM SEXUAL ASSAULT\"). After applying this mapping, we joined the exoneration summary with the cleaned and aggregated Chicago crime data using both year and crime type as keys. The resulting combined dataset allows for side-by-side comparisons of how many people were convicted of certain serious crimes each year and how many were later exonerated, enabling a structured analysis of trends and disparities in the justice system over time.\n\n\n- Whether spikes in reported crimes correlate with spikes in wrongful convictions a few years later.\n\nFrom the chart, there is no clear or consistent lagged correlation between spikes in crime reports and spikes in exonerations. For instance, HOMICIDE counts remain high and relatively stable across the early 2000s (e.g., 667 in 2001, 658 in 2002, 604 in 2003), while exoneration counts for those same conviction years fluctuate without a clear pattern (7 in 2001, 4 in 2002, 2 in 2003). Similarly, BURGLARY had high crime counts (25,623 in 2002), but very few corresponding exonerations (only 1). This suggests that while wrongful convictions are happening, they are not necessarily directly following spikes in reported crime at a systemic or predictable lag.\n\n\n- The types of crimes most commonly associated with exonerations in Cook County, and how those compare to the overall crime landscape in Chicago.\n\nThe data shows that HOMICIDE (mapped to \"Murder\") is by far the most commonly associated crime with exonerations in Cook County. Nearly all years shown in the chart have homicide-related exonerations, with counts ranging from 2 to 7 per year. On the other hand, BURGLARY, while frequently reported (e.g., ~26,000 incidents per year), results in almost no exonerations. Similarly, ROBBERY and SEX OFFENSE categories have few to no exoneration entries despite high occurrence rates. This contrast suggests a disproportionate concentration of wrongful convictions in the most severe crimes, like homicides and sexual assaults. These are often cases with longer sentences and higher investigative scrutiny, where flawed evidence (e.g., eyewitness misidentification, coerced confessions, or prosecutorial misconduct) may have played a significant role and where advocacy efforts focus more intensively.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}