---
title: "Blog Post 2"
description:  |
  Our second blog post containing our progress so far.
author: "Team 10 (Mango)"
date: "2025-03-17"
format: html
---

Data background

The data comes from the National Registry of Exonerations website, which is a collaborative project led by the Newkirk Center for Science & Society. The data is collected by researchers at the University of California Irvine, the University Michigan Law School, and the Michigan State University College of Law from court documents, news reports, and advocacy organizations, and other public sources to track whether a person's conviction is overturned. This dataset is the original source as far as exoneration data goes.

There's no issue with how the data was collected. The sample population is the group of people who have been officially exonerated, but it's not a record of all wrongful convictions, just specifically cases in which someone was able to obtain an exoneration. Because the dataset only includes cases that achieved an exoneration, there's probability that a lot of wrongful convictions never come to attention. Also, because of the publicly available information, some cases may have limited documentation, especially some older ones with fewer resources and publicity.

This data is used to research and analyze the causes and impacts of wrongful convictions, and its findings reflect systemic issues within the criminal justice system. Additionally, it provides a reference for policy-making to help prevent and reduce wrongful convictions while offering support for governance.Some other studies have also utilized the same data. For example, the American Statistical Association (ASA)’s Law and Justice Statistics Section has analyzed the frequency and distribution of wrongful convictions. The research article "Just Data: Advancing the Innocence Movement" also discusses the practical applications of NRE data in real life.The data provided by NRE has been used for policy decisions and has played a significant role in the development of criminal justice policies. Based on NRE data, researchers and policymakers have raised several important questions, such as: How does racial bias influence wrongful convictions? What reforms should be implemented to reduce such injustices? What are the common factors leading to wrongful convictions? The NRE data provides direction for improving the judicial system and helps prevent future miscarriages of justice.

To obtain the data, go to https://www.law.umich.edu/special/exoneration/Pages/Spread-Sheet-Request-Form.aspx and fill out the form using your name and email. Shortly after, the website provides you with an Excel sheet which can be converted to a CSV file. We have included the CSV file in the dataset folder (our dataset is less than 50 MB). We also explored some ways to clean the data in the clean_data.R file in the scripts folder. For the most part, the data is already pretty easy to work with. Our cleaning script performs several key operations on the exoneration dataset. First, it renames column names by replacing spaces with underscores for easier access. It then converts the Age column to an integer, which may result in missing values (NA) if non-numeric entries exist. The Date of Crime Year column is cleaned by removing commas and converting it to an integer. Next, the script replaces all missing values with NA across the dataset, which may affect categorical variables like Tags or Worst Crime Display that might need "Unknown" instead.

